-- DevTrack AI -- MySQL schema reference.
--
-- This is a reference copy of the schema Sequelize creates automatically at
-- startup (`sequelize.sync()` in backend/src/server.js) -- generated by
-- introspecting a live instance, not hand-written, so it's guaranteed to
-- match what the app actually produces. You do not need to run this file
-- manually; it's here for documentation, review, and for anyone who wants to
-- provision the schema without running the Node app first.

CREATE DATABASE IF NOT EXISTS devtrack_ai
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE devtrack_ai;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name           VARCHAR(120)  NOT NULL,
  email          VARCHAR(255)  NOT NULL,
  password       VARCHAR(255)  NOT NULL COMMENT 'bcrypt hash, never plaintext',
  target_company VARCHAR(120)  DEFAULT NULL,
  bio            VARCHAR(500)  DEFAULT NULL,
  created_at     DATETIME NOT NULL,
  updated_at     DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------------
-- problems -- the core Problem Tracker table
-- ---------------------------------------------------------------------------
CREATE TABLE problems (
  id                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id             INT UNSIGNED NOT NULL,
  title               VARCHAR(255) NOT NULL,
  platform            ENUM('LeetCode','GeeksforGeeks','HackerRank','CodeForces','CodeChef','Other')
                       NOT NULL DEFAULT 'Other',
  difficulty          ENUM('Easy','Medium','Hard') NOT NULL,
  topic               VARCHAR(120) NOT NULL,
  status              ENUM('Todo','Attempted','Solved') NOT NULL DEFAULT 'Todo',
  notes               TEXT,
  solved_date         DATE DEFAULT NULL,
  time_spent_minutes  INT UNSIGNED DEFAULT NULL,
  created_at          DATETIME NOT NULL,
  updated_at          DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY problems_user_id (user_id),
  KEY problems_user_id_status (user_id, status),
  KEY problems_user_id_topic (user_id, topic),
  KEY problems_user_id_difficulty (user_id, difficulty),
  CONSTRAINT problems_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------------
-- contests -- Contest Tracker table
-- ---------------------------------------------------------------------------
CREATE TABLE contests (
  id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id          INT UNSIGNED NOT NULL,
  name             VARCHAR(255) NOT NULL,
  platform         ENUM('LeetCode','CodeForces','CodeChef','HackerRank','AtCoder','Other')
                    NOT NULL DEFAULT 'Other',
  contest_date     DATE NOT NULL,
  rating           INT DEFAULT NULL,
  `rank`           INT UNSIGNED DEFAULT NULL,
  problems_solved  INT UNSIGNED NOT NULL DEFAULT 0,
  created_at       DATETIME NOT NULL,
  updated_at       DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY contests_user_id (user_id),
  KEY contests_user_id_contest_date (user_id, contest_date),
  CONSTRAINT contests_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------------
-- goals -- daily/weekly/monthly targets; progress is computed at read time
-- from `problems`, not stored here (avoids stale denormalized counters)
-- ---------------------------------------------------------------------------
CREATE TABLE goals (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id       INT UNSIGNED NOT NULL,
  period        ENUM('daily','weekly','monthly') NOT NULL,
  title         VARCHAR(255) NOT NULL,
  target_topic  VARCHAR(120) DEFAULT NULL COMMENT 'NULL = counts problems of any topic',
  target_count  INT UNSIGNED NOT NULL,
  start_date    DATE NOT NULL,
  end_date      DATE NOT NULL,
  created_at    DATETIME NOT NULL,
  updated_at    DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY goals_user_id (user_id),
  KEY goals_user_id_start_date_end_date (user_id, start_date, end_date),
  CONSTRAINT goals_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------------
-- activities -- one row per user per day with any solve activity; powers
-- the streak calculation and the analytics heatmap without re-scanning
-- `problems` on every request. Kept in sync by backend/src/utils/activitySync.js
-- whenever a problem's status/solvedDate changes.
-- ---------------------------------------------------------------------------
CREATE TABLE activities (
  id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id          INT UNSIGNED NOT NULL,
  activity_date    DATE NOT NULL,
  problems_solved  INT UNSIGNED NOT NULL DEFAULT 0,
  created_at       DATETIME NOT NULL,
  updated_at       DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY activities_user_id_activity_date (user_id, activity_date),
  CONSTRAINT activities_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------------------------------
-- favorites -- many-to-many join between users and problems (a user can only
-- favorite their own problems in practice, enforced at the application layer)
-- ---------------------------------------------------------------------------
CREATE TABLE favorites (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id     INT UNSIGNED NOT NULL,
  problem_id  INT UNSIGNED NOT NULL,
  created_at  DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY favorites_user_id_problem_id (user_id, problem_id),
  KEY problem_id (problem_id),
  CONSTRAINT favorites_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT favorites_ibfk_2 FOREIGN KEY (problem_id) REFERENCES problems (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
